### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by AlePax** [labstreaminglayer/plugin-UE4#3]
Hi there!

I'm trying to get some LSL streams into UE4 using the latest build (Muse2+BlueMuse), but I just can't understand how is this plugin supposed to work...the editor just keeps on crashing whatever BP LSL node I use... is there an example map and/or blueprint you can share, or just some hints on how to get EEG and PPG streams maybe? Thanks in advance!

**Comment by cboulay** [comment]
Before starting with the UE4 plugin, can you confirm that you can access your streams using simpler approaches like LabRecorder and/or pylsl?

**Comment by AlePax** [comment]
Yeah, I can access the streams through BlueMuse, already tested in OpenVibe and I can see / process streams.
For testing purposes I created an actor BP and put it in the scene. The BP has inlet and outlet LSL components in its root.
I'd like to get the heart pulse value from the Muse PPG stream and pass such value to a variable.
EEG stream will be processed through OpenVibe and sent to BCI-UE4 plugin through TCP, but I might consider doing everything with your plugin too.

**Comment by cboulay** [comment]
In the screenshot above you seem to be setup for an Outlet, but that's not what you want. To get the data in from another source (Outlet) you need to create a sink (Inlet). Then you'll have to provide the Inlet with the information it needs to resolve the stream.
In the LSL Bridge screenshot, you can see the info you need: stream names (both use "Muse-83FD") and the types ("EEG", and "PPG").

**Comment by AlePax** [comment]
Mmhmh OK, not working yet... log reports a single value of 0.0.
What am I missing here?
![image](https://user-images.githubusercontent.com/47032041/97999730-fc290980-1deb-11eb-9d0e-c5e46f9d98dc.png)
![image](https://user-images.githubusercontent.com/47032041/97999690-f03d4780-1deb-11eb-9df5-dd5e78e87d37.png)
![image](https://user-images.githubusercontent.com/47032041/97999763-09de8f00-1dec-11eb-83b4-cbea9338c038.png)

**Comment by cboulay** [comment]
I haven't used UE4 in about 6 years so I can't remember what's needed to get the On Stream Updated to be setup correctly. I'm sure you need an Inlet configured but I don't know how you connect that component to the inlet. Anyway, once that's setup correctly, you should be able to run its output into the For Each Loop, then log the individual elements.

Maybe @brifsttar can help?!

**Comment by AlePax** [comment]
Haha, great! 👍 yeah you're right, if things work like that the value is 0.0 upon begin play.
Thanks for the hints anyway, gonna test a little bit more and keep you posted if I ever succeed! :)

**Comment by brifsttar** [comment]
Hi,

I had never tested inlet before, so I just made a PR for a fix (#4). It tested the following BP, it works as intended:

![image](https://user-images.githubusercontent.com/53508707/98009867-54650900-1df6-11eb-89f4-de0c2c882249.png)

**Comment by cboulay** [comment]
Thanks @brifsttar !

@AlePax , just to be clear, the LSLOutlet in @brifsttar 's example is just to generate some dummy data and push it to a stream so the LSLInlet has something to pull from. In your case, you already have an Outlet somewhere else on the network (coming from a muse) so you only need the top part of the blueprint.

**Comment by AlePax** [comment]
Great! Thanks guys, gonna test ASAP! 👍

**Comment by AlePax** [comment]
I run a test with the latest build, but I cannot read the stream from device.... LSLInlet always reports a single 0.0 value and only if I call OnStreamUpdate. When I try the above example BP the simulated LSLOutlet stream works regularly.

I double-checked the device with OpenVibe server / client and it all works. Thanks for the support guys, but I suspect I'm gonna need another way to get PPG stream into UE...

**Comment by cboulay** [comment]
> I double-checked the device with OpenVibe server / client and it all works. 

I don't know what this means. Are you sure this is using an LSL inlet and that it's fetching data?
To verify that the PPG stream is in fact working properly, I would suggest using something that you can be certain is trying to use the LSL inlet in the correct way. I can recommend BrainProducts LSL viewer: https://pressrelease.brainproducts.com/lsl-viewer/

If that shows the PPG data streaming, then yes it's a problem in the UE4 implementation.

**Comment by AlePax** [comment]
> I don't know what this means. Are you sure this is using an LSL inlet and that it's fetching data?
> To verify that the PPG stream is in fact working properly, I would suggest using something that you can be certain is trying to use the LSL inlet in the correct way. I can recommend BrainProducts LSL viewer: https://pressrelease.brainproducts.com/lsl-viewer/
> 
> If that shows the PPG data streaming, then yes it's a problem in the UE4 implementation.

I mean I can see LSL streams perfectly. Gonna test that lsl-viewer too.

**Comment by cboulay** [comment]
Hi @AlePax ,

I finally had an excuse to use this plugin today so I did a little updating and documentation.
* liblsl updated to 1.14
* Using non-blocking ContinuousResolver instead of attempting a blocking resolve every X seconds.
* More detailed example of how to use LSLInput with a float stream.

**Comment by AlePax** [comment]
Great, thanks! :)
Gonna check ASAP!
