### ISSUE TITLE
Distributing on the marketplace

### ISSUE THREAD

**Issue by cboulay** [labstreaminglayer/plugin-UE4#5]
We should probably distribute it on the marketplace. I have no idea how to do that.

After the initial setup, here's a utility that can help with updates:
https://github.com/DrowningDragons/UE4MarketplacePluginAssist

**Comment by brifsttar** [comment]
Sorry I missed that issue, my notifications weren't properly set up.

I've never distributed anything on the MP but I can definitely try it for this plugin. The only question I have is which Epic account to use for publishing. Should I use mine (brifsttar, work account), or is there a generic LSL email address which could be used to create a dedicated account?

**Comment by cboulay** [comment]
There's no generic LSL e-mail. I think it's OK to use your own account. It might look "unofficial" but there's no official alternative so you'll probably still get all the hits.

**Comment by brifsttar** [comment]
As mentioned in #6, I'm in the process of submitting the plugin to the Marketplace. If you have any CC-licensed LSL illustration I could use, that'd be great.

**Comment by cboulay** [comment]
I think this logo might have a relaxed license. I'm trying to find out for sure.

![labstreaminglayer](https://user-images.githubusercontent.com/303797/128603191-bc88d93a-728b-4b3d-8cd8-38a710f51e18.jpg)

By the way, there's a problem with liblsl HEAD. The v1.15.0 tag is fine. I'm guessing the Marketplace entry will include the liblsl shared objects (i.e. lsl.dll, liblsl.dylib, liblsl.so), so it should be fine as long as you use one of the 'releases'.

**Comment by cboulay** [comment]
@trmullen made the logo and he said it can be CC-licensed. Though he's actively seeking a newer/better logo.

**Comment by brifsttar** [comment]
> I'm guessing the Marketplace entry will include the liblsl shared objects (i.e. lsl.dll, liblsl.dylib, liblsl.so), so it should be fine as long as you use one of the 'releases'.

Yes, it's using the 1.14 that's currently in this repo.

Thanks for the logo, I've set it as thumbnail for the package. I've just submitted the package for review by Epic, I'll keep you updated.

**Comment by brifsttar** [comment]
There it is: https://www.unrealengine.com/marketplace/en-US/product/labstreaminglayer-plugin
